# Base configuration
defaults: &defaults
  # number of training epochs
  epochs: 250
  # batch size for inference
  batch_size: 1024
  # stop after "patience" epochs without improvement
  patience: 50
  # directories for output
  model_dir: 'models/oliver_new_local'
  results_dir: 'results/oliver_new_local'

# Dataset configuration
dataset: &dataset
  ## Arguments for external_data
  datafile: '/mnt/home/ophilcox/ceph/separate_bk_data/planck_local_new.txt'
  #planck_template_local.txt'
  
# Model configuration
model: &model
  # number of terms in separable representation
  num_terms: 1
  # type of symmetry
  # 0: 1/6 [ alpha(k1) beta(k2) / alpha(k3) / beta(k3) + 5 perm.]
  # 1: 1/6 [ alpha(k1) beta(k2) gamma(k3) + 5 perm. ]
  # 2: 1/3 [ alpha(k1) beta(k2) beta(k3) + 2 cyc. ]
  # 3: [ alpha(k1) alpha(k2) alpha(k3) ]
  symm_kind: 1
  # whether to add a constant term to the model
  add_bias: false
  # apply log transform to inputs, i.e. use exp(f(log(x))) instead of f(x)
  log_transform: true
  # architecture for alpha, beta, gamma
  sub_arch: 'MLP'
  # type of loss: inner or mse. 
  # inner approximates the true inner product between shapes
  # mse is the standard least squares loss
  loss_func: 'inner'
  # Filtering function
  filterfile: 'planckTE_k_filtering.npy'

# List of experiments (will be run in serial)
experiments:
  # weightD:
  #   <<: *defaults
  #   model_params:
  #     <<: *model
  #   dataset_params:
  #     <<: *dataset    

  # fid:
  #   <<: *defaults
  #   model_params:
  #     <<: *model
  #   dataset_params:
  #     <<: *dataset    
  
  # mse:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     loss_func: 'mse'
  #   dataset_params:
  #      <<: *dataset    

  # cos:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     loss_func: 'cosine'
  #   dataset_params:
  #      <<: *dataset    

  # lin:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     log_transform: false
  #   dataset_params:
  #      <<: *dataset

  # n2:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     num_terms: 2
  #   dataset_params:
  #      <<: *dataset

  # n3:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     num_terms: 3
  #   dataset_params:
  #      <<: *dataset

  # s0:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     symm_kind: 0
  #   dataset_params:
  #      <<: *dataset

  # s2:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     symm_kind: 2
  #   dataset_params:
  #      <<: *dataset

  # s3:
  #   <<: *defaults
  #   description: ""
  #   model_params:
  #     <<: *model
  #     symm_kind: 3
  #   dataset_params:
  #      <<: *dataset